### ISSUE TITLE
add chocolate cake

### ISSUE THREAD

**Issue by mattlub** [foundersandcoders/nazareth-recipes#4]
@Karyum @Suuuuha I think it would be a welcome addition to the desserts roster.

**Comment by Karyum** [comment]
[Easy Chocolate Cake](http://www.10dakot.co.il/%D7%A2%D7%95%D7%92%D7%AA-%D7%9B%D7%93%D7%95%D7%A8%D7%99-%D7%A9%D7%95%D7%A7%D7%95%D7%9C%D7%93/)
I'll make this into a pull request soon

**Comment by m4v15** [comment]
Closing due to merge

**Comment by finnhodgkin** [comment]
The recipe was never added to the readme. Please fix @Karyum.

**Comment by m4v15** [comment]
fair
