### ISSUE TITLE
Arabic Omelette

### ISSUE THREAD

**Issue by Karyum** [foundersandcoders/nazareth-recipes#8]

**Comment by Karyum** [comment]
@finnhodgkin @matthewdking are hatin on this recipe and now hacking intp my account to change it's name 
calling @m4v15 @sofer @mattlub for support

**Comment by m4v15** [comment]
What do you want us to do? There is no recipe at the moment mate, make a PR...

**Comment by Karyum** [comment]
@m4v15 So i was making Arabic omelette today for me and @Suuuuha and then @finnhodgkin and @matthewdking were judging it really hard cause it had the name "Arabic" in it.

So i went to get a drink and left my computer opened **thinking that i can trust people** but they came in and changed the title to just "Omelette".

# Shameful
